name: Go

on:
  push:
    branches: [ master ]
    paths:
      - 'kaybee/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/go.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'kaybee/**'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golint
      run: go get -u golang.org/x/lint/golint

    - name: Install pkger
      run:  go get -u github.com/markbates/pkger/cmd/pkger

    - name: Vet and test
      run: make -C kaybee check

    - name: Build
      run: make -C kaybee build-win build-linux build-macos
